# Generated by Django 5.2.4 on 2025-07-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp_session_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
