# Generated by Django 5.2.4 on 2025-07-18 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('discounts', '0001_initial'),
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='user_specific_discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discount',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='products.brand'),
        ),
        migrations.AddField(
            model_name='discount',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='products.category'),
        ),
        migrations.AddField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='products.product'),
        ),
        migrations.AddField(
            model_name='discount',
            name='sellers',
            field=models.ManyToManyField(blank=True, related_name='seller_discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discount',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='group_discounts', to='auth.group'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.discount'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
